dist: bionic

language: java

jdk:
  - openjdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2/repository/

stages:
  - build
  - name: deploy
    if: (tag IS present) AND (branch = master) AND (type != pull_request)

jobs:
  include:
    - stage: build
      script: mvn -B -Djava.net.useSystemProxies=true clean verify

    - stage: deploy
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - mvn deploy -Ddockerfile.repository=$PLANTUML_DOCKER_REPOSITORY
