debug: false
#spring:
#  jmx:
#    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    info:
      enabled: true

plantuml:
  http:
    localhost:
      url: 'http://localhost:8080'
      username: 'user'
      password: 'secret'