dist: bionic

language: java

jdk:
  - openjdk11

services:
  - docker

stages:
  - build
  - name: deploy
    if: (branch = master) AND (type != pull_request)

jobs:
  include:
    - stage: build
      script: mvn --batch-mode --define java.net.useSystemProxies=true verify

    - stage: deploy
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - mvn clean deploy -Ddockerfile.repository=$PLANTUML_DOCKER_REPOSITORY
