language: java

jdk:
  - openjdk11


services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - mvn clean deploy -Ddockerfile.webcontext=pu